[package]
name = "rusty-dungeon"
version = "0.1.0"
authors = ["Olle Wreede <olle@wreede.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.3"
